# RVV 1.0 Static Lint Script
# Created: 2026-04-03
# Description: Run iverilog syntax check on RVV 1.0 key modules

$RTL_PATH = "..\C910_RTL_FACTORY\gen_rtl _rvv1.0"
$REPORT_PATH = ".\lint_report.md"

$ErrorCount = 0
$WarningCount = 0
$ModulesChecked = 0

function Check-Module {
    param(
        [string]$ModuleName,
        [string[]]$Files
    )
    
    Write-Host "Checking $ModuleName..." -ForegroundColor Cyan
    
    $fileList = $Files -join " "
    $output = & iverilog -g2012 -Wall -tnull $fileList 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  [PASS] No errors" -ForegroundColor Green
        return @{Status="PASS"; Errors=@(); Warnings=@()}
    } else {
        $errors = @()
        $warnings = @()
        
        foreach ($line in $output) {
            if ($line -match "error:") {
                $errors += $line.ToString()
                $script:ErrorCount++
            } elseif ($line -match "warning:") {
                $warnings += $line.ToString()
                $script:WarningCount++
            }
        }
        
        Write-Host "  [FAIL] $($errors.Count) errors, $($warnings.Count) warnings" -ForegroundColor Red
        return @{Status="FAIL"; Errors=$errors; Warnings=$warnings}
    }
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "RVV 1.0 Static Lint Check" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$results = @{}

# Check IDU modules
$results["IDU"] = Check-Module -ModuleName "IDU" -Files @(
    "$RTL_PATH\idu\rtl\ct_idu_id_decd.v",
    "$RTL_PATH\idu\rtl\ct_idu_id_decd_special.v"
)

# Check LSU modules  
$results["LSU"] = Check-Module -ModuleName "LSU" -Files @(
    "$RTL_PATH\lsu\rtl\ct_lsu_ld_ag.v"
)

# Check CP0 modules
$results["CP0"] = Check-Module -ModuleName "CP0" -Files @(
    "$RTL_PATH\cp0\rtl\ct_cp0_regs.v"
)

# Check RTU modules
$results["RTU"] = Check-Module -ModuleName "RTU" -Files @(
    "$RTL_PATH\rtu\rtl\ct_rtu_rob_expt.v"
)

$ModulesChecked = $results.Count
$PassCount = ($results.Values | Where-Object { $_.Status -eq "PASS" }).Count
$FailCount = ($results.Values | Where-Object { $_.Status -eq "FAIL" }).Count

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Modules Checked: $ModulesChecked"
Write-Host "Passed: $PassCount" -ForegroundColor Green
Write-Host "Failed: $FailCount" -ForegroundColor $(if ($FailCount -gt 0) {"Red"} else {"Green"})
Write-Host "Total Errors: $ErrorCount" -ForegroundColor Red
Write-Host "Total Warnings: $WarningCount" -ForegroundColor Yellow

# Generate report
$report = @"
# RVV 1.0 Static Lint Report

## Check Information

| Item | Value |
|------|-------|
| Check Tool | iverilog -g2012 -Wall |
| Check Time | $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") |
| Modules Checked | $ModulesChecked |

---

## Summary

| Level | Count |
|-------|-------|
| Errors | $ErrorCount |
| Warnings | $WarningCount |
| Passed Modules | $PassCount |
| Failed Modules | $FailCount |

---

## Module Results

"@

foreach ($key in $results.Keys) {
    $r = $results[$key]
    $report += "`n### $key Module`n`n"
    $report += "Status: **$($r.Status)**`n`n"
    
    if ($r.Errors.Count -gt 0) {
        $report += "#### Errors`n`n"
        foreach ($e in $r.Errors) {
            $report += "- ``$e```n"
        }
        $report += "`n"
    }
    
    if ($r.Warnings.Count -gt 0) {
        $report += "#### Warnings`n`n"
        foreach ($w in $r.Warnings) {
            $report += "- ``$w```n"
        }
        $report += "`n"
    }
}

$report += @"
---

## Recommendations

1. Fix all syntax errors before synthesis
2. Review warnings for potential issues
3. Ensure all module dependencies are resolved

---

*Report generated by RVV 1.0 Static Lint Script*
"@

$report | Out-File -FilePath $REPORT_PATH -Encoding UTF8
Write-Host ""
Write-Host "Report saved to: $REPORT_PATH" -ForegroundColor Green
