```mermaid
graph TB
    subgraph ct_top["ct_top"]
        subgraph x_ct_core["ct_core"]
            x_ct_ifu_top["ct_ifu_top"]
            x_ct_idu_top["ct_idu_top"]
            x_ct_iu_top["ct_iu_top"]
            x_ct_vfpu_top["ct_vfpu_top"]
            x_ct_lsu_top["ct_lsu_top"]
            x_ct_cp0_top["ct_cp0_top"]
            x_ct_rtu_top["ct_rtu_top"]
        end
        x_ct_mmu_top["ct_mmu_top"]
        x_ct_pmp_top["ct_pmp_top"]
        x_ct_biu_top["ct_biu_top"]
        x_ct_had_private_top["ct_had_private_top"]
        x_ct_hpcp_top["ct_hpcp_top"]
        x_ct_rst_top["ct_rst_top"]
        x_ct_clk_top["ct_clk_top"]
    end
    x_ct_core -->|data| x_ct_mmu_top
    x_ct_mmu_top -->|data| x_ct_pmp_top
    x_ct_pmp_top -->|data| x_ct_biu_top
    x_ct_biu_top -->|data| x_ct_had_private_top
    x_ct_had_private_top -->|data| x_ct_hpcp_top
    x_ct_hpcp_top -->|data| x_ct_rst_top
    x_ct_rst_top -->|data| x_ct_clk_top
    input_pad_biu_acvalid["pad_biu_acvalid"]
    input_pad_biu_acvalid --> ct_top
    input_pad_biu_arready["pad_biu_arready"]
    input_pad_biu_arready --> ct_top
    input_pad_biu_awready["pad_biu_awready"]
    input_pad_biu_awready --> ct_top
    input_pad_biu_bvalid["pad_biu_bvalid"]
    input_pad_biu_bvalid --> ct_top
    input_pad_biu_cdready["pad_biu_cdready"]
    input_pad_biu_cdready --> ct_top
    output_biu_pad_acready["biu_pad_acready"]
    ct_top --> output_biu_pad_acready
    output_biu_pad_arlock["biu_pad_arlock"]
    ct_top --> output_biu_pad_arlock
    output_biu_pad_arvalid["biu_pad_arvalid"]
    ct_top --> output_biu_pad_arvalid
    output_biu_pad_awlock["biu_pad_awlock"]
    ct_top --> output_biu_pad_awlock
    output_biu_pad_awunique["biu_pad_awunique"]
    ct_top --> output_biu_pad_awunique
```